# Generated by Django 4.2.17 on 2025-01-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("department", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField(editable=False)),
            ],
        ),
    ]
