# Generated by Django 4.2.17 on 2025-01-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_employee_age"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="age",),
    ]
